import type { IconType } from 'react-icons'
import { FaAws } from 'react-icons/fa6'
import {
  FiBox,
  FiCheckSquare,
  FiCode,
  FiGitMerge,
  FiGrid,
  FiKey,
  FiLayout,
  FiLock,
  FiServer,
  FiShield,
  FiUserCheck,
  FiUsers,
  FiZap,
  FiDatabase,
  FiBarChart2,
  FiCpu,
  FiTrendingUp,
} from 'react-icons/fi'
import {
  SiAngular,
  SiBootstrap,
  SiCss,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGit,
  SiGithubactions,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiIonic,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJira,
  SiJquery,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMongoose,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNpm,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiReactivex,
  SiRedis,
  SiRedux,
  SiSass,
  SiSocketdotio,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiWebpack,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiElectron,
  SiFlutter,
  SiVercel,
  SiNetlify,
  SiBitbucket,
  SiJsonwebtokens,
  SiNumpy,
  SiPandas,
  SiJupyter,
  SiApachespark,
  SiApacheairflow,
  SiApachekafka,
  SiSnowflake,
  SiGooglebigquery,
  SiDatabricks,
  SiPlotly,
  SiScikitlearn,
  SiSqlite,
  SiPolars,
} from 'react-icons/si'

/** Icon keys usable in site.json (`skills[].items[].icon`) and tutorials.json (`icon`). */
const TECH: Record<string, IconType> = {
  react: SiReact,
  angular: SiAngular,
  nodejs: SiNodedotjs,
  node: SiNodedotjs,
  express: SiExpress,
  mongodb: SiMongodb,
  mongoose: SiMongoose,
  javascript: SiJavascript,
  js: SiJavascript,
  typescript: SiTypescript,
  ts: SiTypescript,
  python: SiPython,
  html: SiHtml5,
  css: SiCss,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  sass: SiSass,
  git: SiGit,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  aws: FaAws,
  gcp: SiGooglecloud,
  firebase: SiFirebase,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  redis: SiRedis,
  nextjs: SiNextdotjs,
  nestjs: SiNestjs,
  redux: SiRedux,
  rxjs: SiReactivex,
  jest: SiJest,
  linux: SiLinux,
  graphql: SiGraphql,
  ionic: SiIonic,
  jquery: SiJquery,
  postman: SiPostman,
  jira: SiJira,
  jenkins: SiJenkins,
  githubactions: SiGithubactions,
  nginx: SiNginx,
  npm: SiNpm,
  vite: SiVite,
  webpack: SiWebpack,
  socketio: SiSocketdotio,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  electron: SiElectron,
  flutter: SiFlutter,
  vercel: SiVercel,
  netlify: SiNetlify,
  bitbucket: SiBitbucket,
  jwt: SiJsonwebtokens,
  numpy: SiNumpy,
  pandas: SiPandas,
  jupyter: SiJupyter,
  spark: SiApachespark,
  airflow: SiApacheairflow,
  kafka: SiApachekafka,
  snowflake: SiSnowflake,
  bigquery: SiGooglebigquery,
  databricks: SiDatabricks,
  plotly: SiPlotly,
  scikitlearn: SiScikitlearn,
  sqlite: SiSqlite,
  polars: SiPolars,
  // Concept skills and topics without a brand logo
  sql: FiDatabase,
  analytics: FiBarChart2,
  dataengineering: FiCpu,
  statistics: FiTrendingUp,
  architecture: FiLayout,
  components: FiGrid,
  performance: FiZap,
  api: FiServer,
  microservices: FiBox,
  cicd: FiGitMerge,
  auth: FiLock,
  sso: FiKey,
  security: FiShield,
  team: FiUsers,
  mentoring: FiUserCheck,
  standards: FiCheckSquare,
}

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '')

/** Resolve an icon by explicit key, falling back to the skill name ("Node.js" → nodejs). */
export function techIcon(key?: string, name?: string): IconType {
  return (key && TECH[norm(key)]) || (name && TECH[norm(name)]) || FiCode
}
